USE MASTER
IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME = 'QLQUANAN')
	DROP DATABASE QLQUANAN
GO
CREATE DATABASE QLQUANAN
GO
USE QLQUANAN
GO
CREATE TABLE DANHMUC
(
	MADANHMUC			CHAR(10)	PRIMARY KEY,
	TENDANHMUC			NVARCHAR(50)
)
GO
CREATE TABLE BAN
(
	IDBAN		INT		IDENTITY		PRIMARY KEY,
	TENBAN		NVARCHAR(20),
	TRANGTHAI	NVARCHAR(20)	DEFAULT N'Trống'
)
GO 
CREATE TABLE MENU
(
	IDMON		INT		IDENTITY		PRIMARY KEY,
	MADANHMUC		CHAR(10)	DEFAULT 'MON',
	TEN		NVARCHAR(100)	DEFAULT N'Chưa đặt tên',
	DONGIA		int DEFAULT 10000
	FOREIGN KEY(MADANHMUC) REFERENCES DANHMUC(MADANHMUC)
)
GO
CREATE TABLE HOADON
(
	IDHOADON	INT		IDENTITY		PRIMARY KEY,
	NGAYLAP		DATEtime,
	IDBAN		INT		NULL,
	TRANGTHAI	NVARCHAR(20)	DEFAULT N'Chưa thanh toán'
	FOREIGN KEY (IDBAN) REFERENCES BAN(IDBAN)
)
GO
CREATE TABLE CHITIETHOADON
(
	ID		INT		IDENTITY		PRIMARY KEY,
	IDHOADON	INT		NOT NULL,
	IDMON		INT		NOT NULL,
	SOLUONG		INT		DEFAULT 1
	FOREIGN KEY (IDHOADON) REFERENCES HOADON(IDHOADON),
	FOREIGN KEY (IDMON) REFERENCES MENU(IDMON)
)
GO



INSERT INTO DANHMUC VALUES( 'MON', N'Món ăn')
INSERT INTO DANHMUC VALUES( 'NUOC', N'Nước uống')
GO



INSERT INTO BAN( TENBAN) VALUES( 'Bàn 1')
INSERT INTO BAN( TENBAN) VALUES( 'Bàn 2')
INSERT INTO BAN( TENBAN, TRANGTHAI) VALUES( 'Bàn 3', N'Có người')
INSERT INTO BAN( TENBAN) VALUES( 'Bàn 4')
INSERT INTO BAN( TENBAN, TRANGTHAI) VALUES( 'Bàn 5', N'Có người')
INSERT INTO BAN( TENBAN) VALUES( 'Bàn 6')
INSERT INTO BAN( TENBAN, TRANGTHAI) VALUES( 'Bàn 7', N'Đã đặt')
INSERT INTO BAN( TENBAN) VALUES( 'Bàn 8')
INSERT INTO BAN( TENBAN) VALUES( 'Bàn 9')
GO



INSERT INTO MENU(TEN, DONGIA) VALUES(N'Khoai tây chiên', 20000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Hotdog', 15000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Pizza', 100000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Bánh tráng nướng', 20000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Cơm cuộn', 30000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Mì cay', 50000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Bánh mì nướng', 10000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Kem', 10000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Gà rán', 75000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Thịt nướng', 50000)
INSERT INTO MENU(TEN, DONGIA) VALUES(N'Xiên que', 5000)
INSERT INTO MENU(MADANHMUC, TEN, DONGIA) VALUES('NUOC', N'Trà sữa', 30000)
INSERT INTO MENU(MADANHMUC, TEN, DONGIA) VALUES('NUOC', N'Sting', 12000)
INSERT INTO MENU(MADANHMUC, TEN, DONGIA) VALUES('NUOC', N'Pepsi', 10000)
INSERT INTO MENU(MADANHMUC, TEN, DONGIA) VALUES('NUOC', N'Nước ép hoa quả', 20000)
INSERT INTO MENU(MADANHMUC, TEN, DONGIA) VALUES('NUOC', N'Cà phê', 10000)
INSERT INTO MENU(MADANHMUC, TEN, DONGIA) VALUES('NUOC', N'Trà đá', 5000)
GO



SET DATEFORMAT DMY
INSERT INTO HOADON(NGAYLAP, IDBAN) VALUES(GETDATE(), 3) 
INSERT INTO HOADON(NGAYLAP, IDBAN) VALUES(GETDATE(), 5) 
INSERT INTO HOADON(NGAYLAP, IDBAN, TRANGTHAI) VALUES('01/01/2020', 5, N'Đã thanh toán') 
INSERT INTO HOADON(NGAYLAP, IDBAN, TRANGTHAI) VALUES('05/11/2019', 1, N'Đã thanh toán')
INSERT INTO HOADON(NGAYLAP, IDBAN, TRANGTHAI) VALUES('29/12/2019', 4, N'Đã thanh toán')
INSERT INTO HOADON(NGAYLAP, IDBAN, TRANGTHAI) VALUES('12/10/2019', 9, N'Đã thanh toán')
INSERT INTO HOADON(NGAYLAP, IDBAN, TRANGTHAI) VALUES('03/01/2020', 4, N'Đã thanh toán')
INSERT INTO HOADON(NGAYLAP, IDBAN, TRANGTHAI) VALUES('13/01/2020', 6, N'Đã thanh toán')
INSERT INTO HOADON(NGAYLAP, IDBAN, TRANGTHAI) VALUES('22/12/2019', 8, N'Đã thanh toán')
GO


INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(1, 3, 1)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(1, 8, 4)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(1, 9, 2)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(2, 10, 3)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(2, 6, 4)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(2, 11, 10)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(2, 2, 5)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(1, 14, 2)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(1, 13, 2)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(2, 14, 3)
INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(2, 15, 2)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 3, 1)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 1, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 4, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 2, 10)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 8, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 10, 3)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 11, 10)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 15, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(3, 13, 2)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 2, 2)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 9, 10)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 11, 20)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 5, 1)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 3, 2)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 1, 7)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 10, 1)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 7, 4)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 17, 3)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(4, 14, 10)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 7, 10)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 9, 8)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 1, 9)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 3, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 6, 4)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 5, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 11, 9)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 8, 4)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 2, 6)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 4, 3)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 17, 6)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(5, 13, 9)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 8, 4)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 9, 6)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 5, 3)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 4, 8)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 3, 2)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 1, 7)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 2, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 10, 4)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 7, 3)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(6, 15, 10)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(7, 5, 8)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(7, 4, 3)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(7, 2, 9)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(7, 9, 6)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(7, 13, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(7, 12, 7)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(8, 5, 6)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(8, 3, 7)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(8, 1, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(8, 2, 6)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(8, 7, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(8, 10, 9)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(8, 16, 2)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(8, 12, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(9, 2, 1)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(9, 3, 5)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(9, 7, 9)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(9, 8, 4)
	INSERT INTO CHITIETHOADON(IDHOADON, IDMON, SOLUONG) VALUES(9, 6, 2)
go



 create proc themmon
 @mahoadon int, @mamon int, @soluong int
 as
 begin
	if exists(select * from chitiethoadon where idhoadon = @mahoadon and idmon = @mamon)
		begin
			declare @slcu int 
			select @slcu = soluong from chitiethoadon where idhoadon = @mahoadon and idmon = @mamon
			declare @tongsl int =  @slcu + @soluong
			if(@tongsl >0)
				update chitiethoadon set soluong = @tongsl where idhoadon = @mahoadon and idmon = @mamon
			else
				delete chitiethoadon where idhoadon = @mahoadon and idmon = @mamon
		end
	else
		insert into chitiethoadon(idhoadon, idmon, soluong) values (@mahoadon, @mamon, @soluong)
 end
 go



 create proc thongke
 as
 begin
	select hd.idhoadon as N'Mã hóa đơn', ngaylap as N'Ngày lập', tongtien as N'Tổng tiền', trangthai as N'Trạng thái'
	from hoadon hd,
		(select idhoadon, sum((soluong * dongia)) as tongtien
		from menu , chitiethoadon ct
		where menu.idmon = ct.idmon
		group by idhoadon) as tong
	where hd.idhoadon = tong.idhoadon
 end
 go



 create proc thongke_DaThanhToan
 as
 begin
	select hd.idhoadon as N'Mã hóa đơn', ngaylap as N'Ngày lập', tongtien as N'Tổng tiền', trangthai as N'Trạng thái'
	from hoadon hd,
		(select idhoadon, sum((soluong * dongia)) as tongtien
		from menu , chitiethoadon ct
		where menu.idmon = ct.idmon
		group by idhoadon) as tong
	where hd.idhoadon = tong.idhoadon and
		   trangthai = N'Đã thanh toán'
 end
 go




 create proc thongke_ChuaThanhToan
 as
 begin
	select hd.idhoadon as N'Mã hóa đơn', ngaylap as N'Ngày lập', tongtien as N'Tổng tiền', trangthai as N'Trạng thái'
	from hoadon hd,
		(select idhoadon, sum((soluong * dongia)) as tongtien
		from menu , chitiethoadon ct
		where menu.idmon = ct.idmon
		group by idhoadon) as tong
	where hd.idhoadon = tong.idhoadon and
		   trangthai = N'Chưa thanh toán'
 end
 go




 create proc xemchitiet(@idhoadon int)
 as
 begin
	select ten, soluong, dongia , (soluong * dongia) as thanhtien
	from hoadon hd, chitiethoadon ct, menu m
	where hd.idhoadon = ct.idhoadon and
		   m.idmon = ct.idmon and 
		   hd.idhoadon = @idhoadon
 end
go


create proc tongtien(@mahoadon int)
as
begin
	select sum((soluong * dongia)) as tongtien
	from menu , chitiethoadon ct
	where menu.idmon = ct.idmon and 
		  idhoadon = @mahoadon
	group by idhoadon
end
go




